### ISSUE TITLE
Will you consider adapting this to the EU Mac OS system?

### ISSUE THREAD

**Issue by pilgrimize** [CatMe0w/zouxian#6]

**Comment by CatMe0w** [comment]
You don't have to! Change the region to United States in system settings and you are good to go.

**Comment by pilgrimize** [comment]
> United
Thanks. This does work. Interestingly, the restrictions on iOS for iPhones and iPads in the EU seem to be deeply integrated into the OS. So I didn't expect it to be so easy to do in macOS.
